# generated by datamodel-codegen:
#   filename:  arclight-protocol.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class ArclightProtocol(RootModel[Any]):
    root: Any = Field(..., title='ArclightProtocol')


class Mode(StrEnum):
    chat = 'chat'
    edit = 'edit'
    test = 'test'


class Input(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: constr(min_length=1)
    agent: Literal['code']
    mode: Mode | None = None
    baseEpoch: conint(ge=0, le=9007199254740991)


class ArcCommand1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    commandId: constr(min_length=1)
    k: Literal['submit']
    sessionId: constr(min_length=1)
    input: Input


class Reason(StrEnum):
    user = 'user'
    abort = 'abort'


class ArcCommand2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    commandId: constr(min_length=1)
    k: Literal['interrupt']
    turnId: constr(min_length=1)
    reason: Reason


class Decision(StrEnum):
    allow = 'allow'
    deny = 'deny'


class Scope(StrEnum):
    once = 'once'
    session = 'session'


class ArcCommand3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    commandId: constr(min_length=1)
    k: Literal['approve']
    askId: constr(min_length=1)
    decision: Decision
    scope: Scope | None = None


class Screenshot(StrEnum):
    none = 'none'
    static = 'static'
    stream = 'stream'


class Background(StrEnum):
    none = 'none'
    limited = 'limited'
    full = 'full'


class FileSystem(StrEnum):
    none = 'none'
    workspace = 'workspace'
    full = 'full'


class Profile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    localSandbox: bool
    screenshot: Screenshot
    background: Background
    fileSystem: FileSystem
    liveSession: bool


class ArcCommand4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    commandId: constr(min_length=1)
    k: Literal['declareCap']
    profile: Profile


class ArcCommand5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    commandId: constr(min_length=1)
    k: Literal['resume']
    sessionId: constr(min_length=1)
    afterSeq: conint(ge=0, le=9007199254740991)
    epoch: conint(ge=0, le=9007199254740991)


class ArcCommand(
    RootModel[ArcCommand1 | ArcCommand2 | ArcCommand3 | ArcCommand4 | ArcCommand5]
):
    root: ArcCommand1 | ArcCommand2 | ArcCommand3 | ArcCommand4 | ArcCommand5


class ArcAck1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: Literal[True]
    commandId: str
    turnId: str | None = None
    sessionId: str | None = None
    status: str | None = None


class Code(StrEnum):
    STALE_EPOCH = 'STALE_EPOCH'
    SESSION_NOT_FOUND = 'SESSION_NOT_FOUND'
    TURN_NOT_FOUND = 'TURN_NOT_FOUND'
    ASK_NOT_FOUND = 'ASK_NOT_FOUND'
    TURN_ACTIVE = 'TURN_ACTIVE'
    VALIDATION = 'VALIDATION'
    UNAUTHORIZED = 'UNAUTHORIZED'
    INTERNAL = 'INTERNAL'


class ArcAck2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    ok: Literal[False]
    commandId: str
    code: Code
    message: str


class ArcAck(RootModel[ArcAck1 | ArcAck2]):
    root: ArcAck1 | ArcAck2


class CapabilityProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    localSandbox: bool
    screenshot: Screenshot
    background: Background
    fileSystem: FileSystem
    liveSession: bool


class SessionStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['session.started']


class TurnStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: constr(min_length=1)
    t: Literal['turn.started']


class Role(StrEnum):
    assistant = 'assistant'


class MessageDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['message.delta']
    messageId: constr(min_length=1)
    role: Role
    delta: str


class UserMessage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['user.message']
    messageId: constr(min_length=1)
    text: str


class ThinkingDelta(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['thinking.delta']
    messageId: constr(min_length=1)
    delta: str


class RiskTier(StrEnum):
    safe = 'safe'
    confirm = 'confirm'
    admin_only = 'admin_only'


class RiskClass(StrEnum):
    read = 'read'
    write = 'write'
    irreversible = 'irreversible'
    funds = 'funds'


class ToolRequested(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['tool.requested']
    callId: constr(min_length=1)
    name: constr(min_length=1)
    argsPreview: str
    riskTier: RiskTier
    riskClass: RiskClass


class Stream(StrEnum):
    stdout = 'stdout'
    stderr = 'stderr'


class ToolProgress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['tool.progress']
    callId: constr(min_length=1)
    stream: Stream
    chunk: str


class Status(StrEnum):
    ok = 'ok'
    error = 'error'


class ErrorClass(StrEnum):
    VALIDATION = 'VALIDATION'
    PERMISSION_DENIED = 'PERMISSION_DENIED'
    APPROVAL_DENIED = 'APPROVAL_DENIED'
    APPROVAL_EXPIRED = 'APPROVAL_EXPIRED'
    SANDBOX_UNAVAILABLE = 'SANDBOX_UNAVAILABLE'
    SANDBOX_DENIED = 'SANDBOX_DENIED'
    TIMEOUT = 'TIMEOUT'
    CANCELLED = 'CANCELLED'
    EXEC_FAILED = 'EXEC_FAILED'
    INTERNAL = 'INTERNAL'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['error']
    tool: str
    error_class: ErrorClass
    user_message: str
    retry_allowed: bool


class ToolOutput(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['tool.output']
    callId: constr(min_length=1)
    status: Status
    preview: str
    spillRef: str | None = None
    error: Error | None = None


class Risk(StrEnum):
    low = 'low'
    med = 'med'
    high = 'high'


class Cls(StrEnum):
    read = 'read'
    write = 'write'
    irreversible = 'irreversible'
    funds = 'funds'


class PermissionAsk(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['permission.ask']
    askId: constr(min_length=1)
    callId: constr(min_length=1)
    risk: Risk
    cls: Cls
    action: constr(min_length=1)
    detail: dict[str, Any]
    expiresAt: conint(le=9007199254740991, gt=0)


class ContextCompacted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['context.compacted']
    summarySeq: conint(le=9007199254740991, gt=0)


class Status1(StrEnum):
    completed = 'completed'
    failed = 'failed'
    interrupted = 'interrupted'


class TurnCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: constr(min_length=1)
    t: Literal['turn.completed']
    status: Status1


class Error1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    status: Literal['error']
    tool: str
    error_class: ErrorClass
    user_message: str
    retry_allowed: bool


class SessionError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['session.error']
    error: Error1


class Interrupted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: constr(min_length=1)
    t: Literal['interrupted']
    reason: Reason


class WorkflowStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.started']
    workflowId: constr(min_length=1)
    name: constr(min_length=1)


class WorkflowPhase(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.phase']
    workflowId: constr(min_length=1)
    title: constr(min_length=1)


class WorkflowAgentStarted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.agent.started']
    workflowId: constr(min_length=1)
    agentId: constr(min_length=1)
    role: constr(min_length=1)
    agentSeq: conint(ge=0, le=9007199254740991)


class Status2(StrEnum):
    ok = 'ok'
    failed = 'failed'


class WorkflowAgentCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.agent.completed']
    workflowId: constr(min_length=1)
    agentId: constr(min_length=1)
    status: Status2


class WorkflowCompleted(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.completed']
    workflowId: constr(min_length=1)


class Reason2(StrEnum):
    error = 'error'
    interrupted = 'interrupted'


class WorkflowFailed(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    v: Literal[1]
    sessionId: constr(min_length=1)
    seq: conint(le=9007199254740991, gt=0)
    epoch: conint(ge=0, le=9007199254740991)
    ts: conint(le=9007199254740991, gt=0)
    turnId: str | None = None
    t: Literal['workflow.failed']
    workflowId: constr(min_length=1)
    reason: Reason2
    message: str
